[project]
name = "panopticon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "lancedb>=0.29.2",
    "mcp>=1.26.0",
    "ollama>=0.6.1",
    "pandas>=3.0.1",
    "pytest>=9.0.2",
    "pyyaml>=6.0.3",
    "typer>=0.24.1",
    "watchfiles>=1.1.1",
]
